version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: echo "A first hello"
      - run: mkdir -p my_workspace && touch output.txt
      - run: echo "Trying out workspaces" > my_workspace/out
      - run: docker build -t abhinav-alpine:ci .
      - run: docker run -it -d  --name myalpine abhinav-alpine:ci sh
      - run: curl https://raw.githubusercontent.com/usr42/clair-container-scan/master/clair-container-scan.sh > clair.sh
      - run: sh clair.sh -p
